export enum ErrorCodeEnum {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    VALIDATION = 'VALIDATION',
    NOT_DELETED = 'NOT_DELETED',
    NOT_UPDATED = 'NOT_UPDATED',
    UNKNOWN = 'UNKNOWN'
}
